export const PROFILES_LIST_REQUEST = 'PROFILES_LIST_REQUEST';
export const PROFILES_LIST_SUCCESS = 'PROFILES_LIST_SUCCESS';
export const PROFILES_LIST_FAIL = 'PROFILES_LIST_FAIL';

export const ALL_PROFILES_LIST_REQUEST = 'ALL_PROFILES_LIST_REQUEST';
export const ALL_PROFILES_LIST_SUCCESS = 'ALL_PROFILES_LIST_SUCCESS';
export const ALL_PROFILES_LIST_FAIL = 'ALL_PROFILES_LIST_FAIL';